{% set name = "microsoft-kiota-serialization-multipart" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_serialization_multipart-{{ version }}.tar.gz
  sha256: 38fec8a75f953335bf00165789e82f6b56176f552e598feceefb0adc3d347c47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.8,<4.0
    - microsoft-kiota-abstractions
    - pendulum >=3.0.0b1

test:
  imports:
    - kiota_serialization_multipart
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-python/tree/main/packages/serialization/multipart
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
